stages:
    - build
    - run

.deploy-template:
    stage: build
    script:
        # set variables (need to set domain_name in variables)
        - release_dir_name="$(date +'%Y%m%d%H%M%S')"
        # service variables
        - release_dir=$(dirname "$(pwd)")/${domain_name}/$release_dir_name
        - repo_dir=$(pwd)
        - domain_dir=/var/www/${domain_name}
        - storage_dir=$domain_dir/storage
        # user check
        - whoami
        # ...building the app
        - cp -rv ${env_file} .env
        - /home/devops/.bun/bin/bun i
        - /home/devops/.bun/bin/bun run build
        # ...moving current build into release dir
        - mv $repo_dir $release_dir
        # create symlink
        - ln -snf $release_dir $domain_dir/app
    tags:
        - roosters-runner

.run-template:
    stage: run
    script:
        # set variables (need to set domain_name and env in variables)
        - cd /var/www/${domain_name}/app
        - pm2 delete ${app_name}
        - pm2 startOrReload ${env}.ecosystem.config.cjs
    tags:
        - roosters-runner

stage-build:
    extends: .deploy-template
    only:
        - develop
    variables:
        app_name: 'StageClient'
        domain_name: 'stage.roosters-dev.ru'
        env_file: '$STAGE_ENV_FILE'

stage-run:
    extends: .run-template
    only:
        - develop
    variables:
        app_name: 'StageClient'
        domain_name: 'stage.roosters-dev.ru'
        env: 'stage'

production-build:
    extends: .deploy-template
    only:
        - master
    variables:
        app_name: 'ProductionClient'
        domain_name: 'roosters-dev.ru'
        env_file: '$PRODUCTION_ENV_FILE'

production-run:
    extends: .run-template
    only:
        - master
    variables:
        app_name: 'ProductionClient'
        domain_name: 'roosters-dev.ru'
        env: 'production'
