export type BtnModifier =
    | 'primary'
    | 'secondary'
    | 'outline'
    | 'outline-secondary'
    | 'third'
    | 'success'
    | 'warning'
    | 'grey'
    | 'item'
    | 'item-white'
    | 'sm'
    | 'lg'
    | 'xl'
    | 'disabled'
    | 'icon'
    | 'single-icon';
